//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LayerDetail
    {
        public LayerDetail()
        {
            this.CoverageDetails = new HashSet<CoverageDetail>();
        }
    
        public int LayerId { get; set; }
        public Nullable<System.Guid> SubmissionId { get; set; }
        public string LayerName { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
    
        public virtual ICollection<CoverageDetail> CoverageDetails { get; set; }
        public virtual Submission Submission { get; set; }
    }
}
