//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyDetail
    {
        public PolicyDetail()
        {
            this.Submissions = new HashSet<Submission>();
        }
    
        public int PolicyId { get; set; }
        public Nullable<bool> IsBindDate { get; set; }
        public Nullable<System.DateTime> BindDate { get; set; }
        public string Renewable { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public string AdmittedTypeCode { get; set; }
        public Nullable<bool> IsCompanyPaperType { get; set; }
        public string CompanyPaperTypeCode { get; set; }
        public Nullable<bool> IsCompanyPaperNumber { get; set; }
        public string CompanyPaperNumberTypeCode { get; set; }
        public string PolicySymbol { get; set; }
        public Nullable<bool> IsPolicyNumber { get; set; }
        public string PolicyNumber { get; set; }
        public string SuffixCode { get; set; }
        public string LTACode { get; set; }
        public Nullable<short> RiskCountryId { get; set; }
        public string MasterPolicyNumber { get; set; }
        public Nullable<int> FormTypeId { get; set; }
        public string OffOnShoreCode { get; set; }
        public Nullable<System.Guid> ProcessIdentifier { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifedOnDate { get; set; }
        public string LastModifiedByUserId { get; set; }
    
        public virtual ICollection<Submission> Submissions { get; set; }
    }
}
