//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PremiumDetail
    {
        public PremiumDetail()
        {
            this.CoverageDetails = new HashSet<CoverageDetail>();
            this.Submissions = new HashSet<Submission>();
        }
    
        public int PremiumId { get; set; }
        public Nullable<System.DateTime> ExchangeRateDate { get; set; }
        public Nullable<decimal> LayerPercent { get; set; }
        public Nullable<decimal> PolicyCommissionPercent { get; set; }
        public string OriginalCurrencyCode { get; set; }
        public Nullable<decimal> OriginalLayerLimit { get; set; }
        public Nullable<bool> IsOriginalAttachmentPoint { get; set; }
        public Nullable<decimal> OriginalAttachmentPoint { get; set; }
        public string TransactionalCurrencyCode { get; set; }
        public Nullable<decimal> ConversionRateToTransactional { get; set; }
        public Nullable<decimal> TransactionalSIR { get; set; }
        public Nullable<decimal> TransactionalDeductible { get; set; }
        public Nullable<decimal> TransactionalGrossPremium { get; set; }
        public Nullable<decimal> TransactionalCollections { get; set; }
        public Nullable<decimal> TransactionalDeductions { get; set; }
        public Nullable<decimal> TransactionalGSTIN { get; set; }
        public Nullable<decimal> TransactionalGSTOUT { get; set; }
        public Nullable<bool> IsTransactionalTIV { get; set; }
        public Nullable<decimal> TransactionalTIV { get; set; }
        public string JurCurrencyCode { get; set; }
        public Nullable<decimal> JurExchangeRate { get; set; }
        public Nullable<decimal> USDExchangeRate { get; set; }
        public string PremiumType { get; set; }
        public Nullable<System.Guid> ProcessIdentifier { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifedOnDate { get; set; }
        public string LastModifiedByUserId { get; set; }
        public string Installment { get; set; }
    
        public virtual ICollection<CoverageDetail> CoverageDetails { get; set; }
        public virtual ICollection<Submission> Submissions { get; set; }
    }
}
