//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.Entities.MDMEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerParty
    {
        public BrokerParty()
        {
            this.BrokerAddresses = new HashSet<BrokerAddress>();
            this.BrokerProductLines = new HashSet<BrokerProductLine>();
            this.BrokerProductLineSubTypes = new HashSet<BrokerProductLineSubType>();
        }
    
        public System.Guid BrokerPartyId { get; set; }
        public int Cityid { get; set; }
        public string BrokerEntityName { get; set; }
        public string BrokerEntityDescription { get; set; }
        public string BrokerFullCode { get; set; }
        public string BrokerStreetAddressLine1 { get; set; }
        public string BrokerStreetAddressLine2 { get; set; }
        public string BrokerZipCode { get; set; }
        public string SourceSystemName { get; set; }
        public string SourceSystemId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
        public Nullable<System.Guid> brokerid { get; set; }
        public Nullable<System.Guid> BrokerType { get; set; }
        public Nullable<System.Guid> Wholesaler { get; set; }
    
        public virtual Broker Broker { get; set; }
        public virtual ICollection<BrokerAddress> BrokerAddresses { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<BrokerProductLine> BrokerProductLines { get; set; }
        public virtual ICollection<BrokerProductLineSubType> BrokerProductLineSubTypes { get; set; }
    }
}
