//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.Entities.MDMEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Projects = new HashSet<Project>();
            this.InsuredAddresses = new HashSet<InsuredAddress>();
            this.Branches = new HashSet<Branch>();
            this.BrokerParties = new HashSet<BrokerParty>();
        }
    
        public int CityId { get; set; }
        public string CityName { get; set; }
        public string CityCode { get; set; }
        public short StateId { get; set; }
        public string SourceSystemName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
        public Nullable<int> RegionId { get; set; }
    
        public virtual ICollection<Project> Projects { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<InsuredAddress> InsuredAddresses { get; set; }
        public virtual ICollection<Branch> Branches { get; set; }
        public virtual ICollection<BrokerParty> BrokerParties { get; set; }
    }
}
