//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.Entities.MDMEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormType
    {
        public int ID { get; set; }
        public Nullable<int> ProductLineId { get; set; }
        public string FormTypeName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
