//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.Entities.MDMEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuredAddress
    {
        public System.Guid Id { get; set; }
        public System.Guid Partyid { get; set; }
        public int CityId { get; set; }
        public string Addressline1 { get; set; }
        public string Addressline2 { get; set; }
        public string Zipcode { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string AddressTypeId { get; set; }
        public Nullable<bool> IsPrimaryAddress { get; set; }
        public string HomePhone { get; set; }
        public string Addressline3 { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string SourceSystemName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
        public Nullable<int> AdvisenID { get; set; }
        public string DBNumber { get; set; }
    
        public virtual City City { get; set; }
    }
}
