//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.Entities.MDMEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterInsureds_Backup_2802016
    {
        public System.Guid MasterInsuredID { get; set; }
        public string Name { get; set; }
        public string Ticker { get; set; }
        public Nullable<long> Revenue { get; set; }
        public Nullable<long> AdvisenID { get; set; }
        public Nullable<long> GUPAdvisenID { get; set; }
        public bool IsGUP { get; set; }
        public Nullable<System.Guid> GUPInsuredID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
    }
}
