//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.Entities.MDMEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicySymbol
    {
        public int PolicySymbolId { get; set; }
        public string PolicySymbol1 { get; set; }
        public Nullable<short> RegionId { get; set; }
    
        public virtual Region Region { get; set; }
    }
}
