//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.Entities.MDMEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLine
    {
        public ProductLine()
        {
            this.BrokerProductLines = new HashSet<BrokerProductLine>();
            this.Coverages = new HashSet<Coverage>();
            this.PolicyTypes = new HashSet<PolicyType>();
            this.ProductLineSubTypes = new HashSet<ProductLineSubType>();
            this.UnderwriterProductLines = new HashSet<UnderwriterProductLine>();
        }
    
        public short ProductLineId { get; set; }
        public string ProductLineName { get; set; }
        public string ProductLineCode { get; set; }
        public string SourceSystemName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
    
        public virtual ICollection<BrokerProductLine> BrokerProductLines { get; set; }
        public virtual ICollection<Coverage> Coverages { get; set; }
        public virtual ICollection<PolicyType> PolicyTypes { get; set; }
        public virtual ICollection<ProductLineSubType> ProductLineSubTypes { get; set; }
        public virtual ICollection<UnderwriterProductLine> UnderwriterProductLines { get; set; }
    }
}
