//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.Entities.MDMEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfitCode
    {
        public short ProfitCodeId { get; set; }
        public string ProfitCodeName { get; set; }
        public string ProfitCodeDescription { get; set; }
        public Nullable<short> SourceSystemId { get; set; }
        public string ISOCGName { get; set; }
        public short SectionCodeId { get; set; }
        public string SourceSystemName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
        public string Code { get; set; }
    
        public virtual SectionCode SectionCode { get; set; }
    }
}
