//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.Entities.MDMEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.CurrencyRegions = new HashSet<CurrencyRegion>();
            this.Branches = new HashSet<Branch>();
            this.PolicySymbols = new HashSet<PolicySymbol>();
            this.Underwriters = new HashSet<Underwriter>();
        }
    
        public short RegionId { get; set; }
        public string RegionName { get; set; }
        public string RegionDescription { get; set; }
        public string SourceSystemName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
        public string RegionCode { get; set; }
    
        public virtual ICollection<CurrencyRegion> CurrencyRegions { get; set; }
        public virtual ICollection<Branch> Branches { get; set; }
        public virtual ICollection<PolicySymbol> PolicySymbols { get; set; }
        public virtual ICollection<Underwriter> Underwriters { get; set; }
    }
}
