//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.Entities.MDMEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Underwriter
    {
        public Underwriter()
        {
            this.UnderwriterProductLines = new HashSet<UnderwriterProductLine>();
            this.UnderwriterProductSubLines = new HashSet<UnderwriterProductSubLine>();
        }
    
        public int UnderwriterId { get; set; }
        public string UnderwriterName { get; set; }
        public string UnderwriterDescription { get; set; }
        public short RegionId { get; set; }
        public string SourceSystemName { get; set; }
        public Nullable<int> SourceSystemId { get; set; }
        public bool IsActive { get; set; }
        public string EmailId { get; set; }
        public string WindowsLogin { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual ICollection<UnderwriterProductLine> UnderwriterProductLines { get; set; }
        public virtual ICollection<UnderwriterProductSubLine> UnderwriterProductSubLines { get; set; }
    }
}
