//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.BusinessEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerPartyModel
    {
        public BrokerPartyModel()
        {
            this.BrokerAddresses = new List<BrokerAddressModel>();
            this.BrokerProductLines = new List<BrokerProductLineModel>();
            this.BrokerProductLineSubTypes = new List<BrokerProductLineSubTypeModel>();
        }
    
        public System.Guid BrokerPartyId { get; set; }
        public int Cityid { get; set; }
        public string BrokerEntityName { get; set; }
        public string BrokerEntityDescription { get; set; }
        public string BrokerFullCode { get; set; }
        public string BrokerStreetAddressLine1 { get; set; }
        public string BrokerStreetAddressLine2 { get; set; }
        public string BrokerZipCode { get; set; }
        public string SourceSystemName { get; set; }
        public string SourceSystemId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
        public Nullable<System.Guid> brokerid { get; set; }
        public Nullable<System.Guid> BrokerType { get; set; }
        public Nullable<System.Guid> Wholesaler { get; set; }
    
        public virtual BrokerModel Broker { get; set; }
        public virtual List<BrokerAddressModel> BrokerAddresses { get; set; }
        public virtual CityModel City { get; set; }
        public virtual List<BrokerProductLineModel> BrokerProductLines { get; set; }
        public virtual List<BrokerProductLineSubTypeModel> BrokerProductLineSubTypes { get; set; }
    }
}
