//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.BusinessEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerProductLineModel
    {
        public int Id { get; set; }
        public short ProductLineId { get; set; }
        public System.Guid BrokerPartyId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.Guid TypeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
    
        public virtual BrokerPartyModel BrokerParty { get; set; }
        public virtual ProductLineModel ProductLine { get; set; }
    }
}
