//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.BusinessEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerModel
    {
        public BrokerModel()
        {
            this.BrokerParties = new List<BrokerPartyModel>();
        }
    
        public string BrokerName { get; set; }
        public string BrokerDescription { get; set; }
        public string BrokerCode { get; set; }
        public Nullable<int> ParentBrokerId { get; set; }
        public Nullable<int> AdvisenId { get; set; }
        public string SourceSystemName { get; set; }
        public string SourceSystemId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
        public System.Guid BrokerId { get; set; }
    
        public virtual List<BrokerPartyModel> BrokerParties { get; set; }
    }
}
