//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.BusinessEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityModel
    {
        public CityModel()
        {
            this.Projects = new List<ProjectModel>();
            this.InsuredAddresses = new List<InsuredAddressModel>();
            this.Branches = new List<BranchModel>();
            this.BrokerParties = new List<BrokerPartyModel>();
        }
    
        public int CityId { get; set; }
        public string CityName { get; set; }
        public string CityCode { get; set; }
        public short StateId { get; set; }
        public string SourceSystemName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
        public Nullable<int> RegionId { get; set; }
    
        public virtual List<ProjectModel> Projects { get; set; }
        public virtual StateModel State { get; set; }
        public virtual List<InsuredAddressModel> InsuredAddresses { get; set; }
        public virtual List<BranchModel> Branches { get; set; }
        public virtual List<BrokerPartyModel> BrokerParties { get; set; }
    }
}
