//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.BusinessEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryModel
    {
        public CountryModel()
        {
            this.States = new List<StateModel>();
        }
    
        public short CountryId { get; set; }
        public string CountryName { get; set; }
        public string CountryDescription { get; set; }
        public string CountryNumericCode { get; set; }
        public string ISOCountry3Code { get; set; }
        public string ISOCountry2Code { get; set; }
        public string LocalCurrencyCode { get; set; }
        public string SourceSystemName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
    
        public virtual List<StateModel> States { get; set; }
    }
}
