//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.BusinessEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoverageDetailModel
    {
        public int CoverageDetailId { get; set; }
        public Nullable<int> LayerId { get; set; }
        public Nullable<int> CoverageId { get; set; }
        public Nullable<int> PremiumId { get; set; }
    
        public virtual LayerDetailModel LayerDetail { get; set; }
        public virtual PremiumDetailModel PremiumDetail { get; set; }
    }
}
