//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.BusinessEntities.Models
{
    using System;
    
    public partial class GetPolicyTypeList_Model
    {
        public int PolicyTypeId { get; set; }
        public string AttachmentType { get; set; }
        public string PolicyType { get; set; }
        public string CoverageVersion { get; set; }
        public string PolicySymbol { get; set; }
        public string PolicyCode { get; set; }
        public string PolicySymbolDescription { get; set; }
    }
}
