//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.BusinessEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuredPartyModel
    {
        public InsuredPartyModel()
        {
            this.ContactPersonInsureds = new List<ContactPersonInsuredModel>();
            this.InsuredAlias = new List<InsuredAliaModel>();
        }
    
        public System.Guid PartyId { get; set; }
        public string Name { get; set; }
        public Nullable<int> AdvisenId { get; set; }
        public string DBNumber { get; set; }
        public Nullable<System.DateTime> InActivationDate { get; set; }
        public string Status { get; set; }
        public Nullable<long> ParentInsuredId { get; set; }
        public bool IsActive { get; set; }
        public string SourceSystemName { get; set; }
        public string SourceSystemId { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
        public string NAICCode { get; set; }
        public string SICCode { get; set; }
        public Nullable<int> GUPAdvisenID { get; set; }
        public Nullable<System.Guid> GUPId { get; set; }
        public Nullable<bool> IsGUP { get; set; }
    
        public virtual List<ContactPersonInsuredModel> ContactPersonInsureds { get; set; }
        public virtual List<InsuredAliaModel> InsuredAlias { get; set; }
    }
}
