//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.BusinessEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLineSubTypeModel
    {
        public ProductLineSubTypeModel()
        {
            this.BrokerProductLineSubTypes = new List<BrokerProductLineSubTypeModel>();
            this.UnderwriterProductSubLines = new List<UnderwriterProductSubLineModel>();
            this.SectionCodes = new List<SectionCodeModel>();
        }
    
        public int ProductLineSubTypeId { get; set; }
        public string ProductLineSubTypeName { get; set; }
        public string ProductLineSubTypeDescription { get; set; }
        public short ProductLineId { get; set; }
        public string SourceSystemName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
        public string Code { get; set; }
    
        public virtual List<BrokerProductLineSubTypeModel> BrokerProductLineSubTypes { get; set; }
        public virtual List<UnderwriterProductSubLineModel> UnderwriterProductSubLines { get; set; }
        public virtual ProductLineModel ProductLine { get; set; }
        public virtual List<SectionCodeModel> SectionCodes { get; set; }
    }
}
