//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.BusinessEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusModel
    {
        public StatusModel()
        {
            this.Reasoncodes = new List<ReasoncodeModel>();
            this.Reasoncodes1 = new List<ReasoncodeModel>();
        }
    
        public int StatusId { get; set; }
        public string StatusName { get; set; }
        public string StatusDescription { get; set; }
        public string StatusCategory { get; set; }
        public string SourceSystemName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public string CreatedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifedOnDate { get; set; }
        public string LastModifiedByUserId { get; set; }
    
        public virtual List<ReasoncodeModel> Reasoncodes { get; set; }
        public virtual List<ReasoncodeModel> Reasoncodes1 { get; set; }
    }
}
