//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.BusinessEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmissionHeaderModel
    {
        public SubmissionHeaderModel()
        {
            this.Submissions = new List<SubmissionModel>();
        }
    
        public System.Guid SubmissionHeaderId { get; set; }
        public string SubmissionNumber { get; set; }
        public string PolicyNumber { get; set; }
        public string IsDuckSubmissionNumber { get; set; }
        public string DuckSubmissionNumber { get; set; }
        public string SourceSystemName { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
        public Nullable<System.Guid> ProcessIdentifier { get; set; }
    
        public virtual List<SubmissionModel> Submissions { get; set; }
    }
}
