//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.BusinessEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmissionModel
    {
        public SubmissionModel()
        {
            this.AdditionalCedants = new List<AdditionalCedantModel>();
            this.AdditionalInsureds = new List<AdditionalInsuredModel>();
            this.LayerDetails = new List<LayerDetailModel>();
            this.QCStatusHistories = new List<QCStatusHistoryModel>();
            this.SubmissionCoverages = new List<SubmissionCoverageModel>();
        }
    
        public System.Guid SubmissionId { get; set; }
        public System.Guid SubmissionHeaderId { get; set; }
        public string SubmissionNumber { get; set; }
        public string NewRenewalTypeCode { get; set; }
        public short RegionId { get; set; }
        public int ProfitCenterUnderWriterId { get; set; }
        public int IssuingUnderWriterId { get; set; }
        public short ProductLineTypeId { get; set; }
        public short ProductLineSubTypeId { get; set; }
        public short SectionCodeId { get; set; }
        public short ProfitCodeId { get; set; }
        public string AttachmentTypeCode { get; set; }
        public int CurrentStatusId { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public System.Guid InsuredId { get; set; }
        public Nullable<System.Guid> InsuredAddressId { get; set; }
        public Nullable<int> InsuredAliasId { get; set; }
        public Nullable<bool> IsDifferentDBA { get; set; }
        public string DBAName { get; set; }
        public string PriorityCompanyCode { get; set; }
        public string DirectAssumedTypeCode { get; set; }
        public string CedantName { get; set; }
        public Nullable<short> DomicileStateId { get; set; }
        public string AssumedEntityType { get; set; }
        public System.Guid BrokerEntityId { get; set; }
        public Nullable<System.Guid> RetailBrokerID { get; set; }
        public Nullable<System.Guid> BrokerContactPersonId { get; set; }
        public string IncumbentAttackingBrokerType { get; set; }
        public Nullable<bool> IsBy_Berk_SI_FROM_Broker { get; set; }
        public Nullable<System.DateTime> By_Berk_SI_FROM_Broker { get; set; }
        public Nullable<bool> IsBy_India_FROM_Berk_SI { get; set; }
        public Nullable<System.DateTime> By_India_FROM_Berk_SI { get; set; }
        public string ProfitCentreOffice { get; set; }
        public string IssuingOffice { get; set; }
        public Nullable<bool> IsUnclearAccount { get; set; }
        public Nullable<System.Guid> ReasonID { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<int> PolicyTypeID { get; set; }
        public Nullable<int> CoverageID { get; set; }
        public string SixDigitSubmissionNumber { get; set; }
        public string RenewalofPolicyNumber { get; set; }
        public Nullable<System.Guid> ParentSubmissionId { get; set; }
        public Nullable<System.Guid> ProcessIdentifier { get; set; }
        public Nullable<int> PolicyId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> PremiumId { get; set; }
        public Nullable<int> QCStatusId { get; set; }
        public Nullable<System.DateTime> QCApprovaldate { get; set; }
        public string QCRemark { get; set; }
        public Nullable<System.Guid> ImmediateParentId { get; set; }
        public string AffiliationsCode { get; set; }
        public string MarketSegmentCode { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifedOnDate { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
    
        public virtual List<AdditionalCedantModel> AdditionalCedants { get; set; }
        public virtual List<AdditionalInsuredModel> AdditionalInsureds { get; set; }
        public virtual List<LayerDetailModel> LayerDetails { get; set; }
        public virtual PolicyDetailModel PolicyDetail { get; set; }
        public virtual ProjectDetailModel ProjectDetail { get; set; }
        public virtual List<QCStatusHistoryModel> QCStatusHistories { get; set; }
        public virtual SubmissionHeaderModel SubmissionHeader { get; set; }
        public virtual PremiumDetailModel PremiumDetail { get; set; }
        public virtual List<SubmissionCoverageModel> SubmissionCoverages { get; set; }
    }
}
