//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.BusinessEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmissionCoverageModel
    {
        public int SubmissionCoverageId { get; set; }
        public System.Guid SubmissionId { get; set; }
        public int CoverageId { get; set; }
        public string CoverageCode { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.Guid> ProcessIdentifier { get; set; }
    
        public virtual SubmissionModel Submission { get; set; }
    }
}
