//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.BusinessEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSessionLogModel
    {
        public System.Guid Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string SessionString { get; set; }
        public Nullable<bool> SessionStatus { get; set; }
        public string SessionIP { get; set; }
        public string SessionMedia { get; set; }
        public string SessionBrowser { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
    }
}
