//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.BusinessEntities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegionModel
    {
        public int id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string RegionName { get; set; }
    
        public virtual UserModel User { get; set; }
    }
}
