//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.BusinessEntities.Models
{
    using System;
    
    public partial class USP_ExportSubmission_Model
    {
        public string Work_item__submission_no_ { get; set; }
        public string New_Renewal { get; set; }
        public Nullable<System.DateTime> Date_of_Renewal { get; set; }
        public string Renewable__Y_N_ { get; set; }
        public string Master_Policy_Number { get; set; }
        public string Renewal_of__Policy_Number_ { get; set; }
    }
}
