//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace International.BusinessEntities.Models
{
    using System;
    
    public partial class USP_GetGroups_Model
    {
        public int Id { get; set; }
        public string GroupName { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CreatedOnDate { get; set; }
        public string CreatedByUserId { get; set; }
        public string LastModifedOnDate { get; set; }
        public string LastModifiedByUserId { get; set; }
    }
}
